const fs = require('fs');
const file = 'c:/Users/diwas/OneDrive/Documents/Desktop/school management saraswati/html/admin-portal.html';
let content = fs.readFileSync(file, 'utf8');

// 1. Add module schema
const schemaInjection = `      "Academic_Report": {
        headers: ["Report Title", "Module Area", "Generated By", "Status"],
        fields: [
          { id: "f1", label: "Report Title", type: "text", placeholder: "e.g. End of Year Financial" },
          { id: "f2", label: "Module Area", type: "select", options: ["Finance", "Academic", "Inventory", "HR"] },
          { id: "f3", label: "Generated By", type: "text", placeholder: "e.g. Admin" },
          { id: "f4", label: "Status", type: "select", options: ["Draft", "Published"] },
          { id: "f5", label: "Report File URL", type: "text", placeholder: "e.g. https://link-to-pdf.com", required: false }
        ]
      },
      "Academic_TeacherProfiles": {
        headers: ["Name", "Role", "Email", "Status"],
        fields: [
          { id: "f1", label: "Full Name", type: "text", placeholder: "e.g. Hari Karki" },
          { id: "f2", label: "Designation / Role", type: "text", placeholder: "e.g. Principal / Math Teacher" },
          { id: "f3", label: "Email Address", type: "text", placeholder: "e.g. hari@school.com", required: false },
          { id: "f4", label: "Phone Number", type: "text", placeholder: "e.g. 9840000000", required: false },
          { id: "f5", label: "Description / Bio", type: "text", placeholder: "e.g. Dedicated educator with 10 years experience", required: false },
          { id: "f6", label: "Photo / Image URL", type: "text", placeholder: "e.g. https://imgur.com/... (Direct Image Link)", required: false },
          { id: "f7", label: "Status", type: "select", options: ["Active", "Inactive"] }
        ]
      },`;

// Replace Academic_Report schema block with both Report and TeacherProfiles
const oldReportSchema = `"Academic_Report": {
        headers: ["Report Title", "Module Area", "Generated By", "Status"],
        fields: [
          { id: "f1", label: "Report Title", type: "text", placeholder: "e.g. End of Year Financial" },
          { id: "f2", label: "Module Area", type: "select", options: ["Finance", "Academic", "Inventory", "HR"] },
          { id: "f3", label: "Generated By", type: "text", placeholder: "e.g. Admin" },
          { id: "f4", label: "Status", type: "select", options: ["Draft", "Published"] },
          { id: "f5", label: "Report File URL", type: "text", placeholder: "e.g. https://link-to-pdf.com", required: false }
        ]
      },`;

if (content.includes(oldReportSchema)) {
    content = content.replace(oldReportSchema, schemaInjection);
} else {
    console.log("Could not find oldReportSchema!");
}

// 2. Modify sidebar to add Public Faculty Profiles link
const sidebarInjection = `<a class="submenu-link" onclick="switchPage('generic-crud', this); renderGenericModule('Academic_TeacherProfiles')">Public Faculty Profiles</a>
            <a class="submenu-link" onclick="switchPage('generic-crud', this); renderGenericModule('Academic_Categories')">Manage Categories</a>`;

if (content.includes(`<a class="submenu-link" onclick="switchPage('generic-crud', this); renderGenericModule('Academic_Categories')">Manage Categories</a>`)) {
    content = content.replace(`<a class="submenu-link" onclick="switchPage('generic-crud', this); renderGenericModule('Academic_Categories')">Manage Categories</a>`, sidebarInjection);
} else {
    console.log("Could not find Manage Categories link in sidebar!");
}

// 3. Modify renderGenericTable
const renderInjection = `      } else if (currentGenericModule === 'Academic_Report' && supabaseDb) {
        try {
          const { data: repData, error } = await supabaseDb.from('reports').select('*').order('created_at', { ascending: false });
          if (!error && repData) {
            data = repData.map(r => ({ id: r.id, f1: r.report_title, f2: r.module_area, f3: r.generated_by, f4: r.status, f5: r.file_url }));
          }
        } catch(err) { console.error(err); data = []; }
      } else if (currentGenericModule === 'Academic_TeacherProfiles' && supabaseDb) {
        try {
          const { data: tData, error } = await supabaseDb.from('teacher_profiles').select('*').order('id', { ascending: false });
          if (!error && tData) {
            data = tData.map(t => ({ id: t.id, f1: t.teacher_name, f2: t.teacher_role, f3: t.teacher_email, f4: t.teacher_phone, f5: t.teacher_description, f6: t.teacher_image_url, f7: t.is_active ? 'Active' : 'Inactive' }));
          }
        } catch(err) { console.error(err); data = []; }
      } else {`;

content = content.replace(`      } else if (currentGenericModule === 'Academic_Report' && supabaseDb) {
        try {
          const { data: repData, error } = await supabaseDb.from('reports').select('*').order('created_at', { ascending: false });
          if (!error && repData) {
            data = repData.map(r => ({ id: r.id, f1: r.report_title, f2: r.module_area, f3: r.generated_by, f4: r.status, f5: r.file_url }));
          }
        } catch(err) { console.error(err); data = []; }
      } else {`, renderInjection);

// 4. Modify handleGenericSubmit
const submitInjection = `      } else if (currentGenericModule === 'Academic_Report' && supabaseDb) {
        try {
          let repData = { report_title: entry.f1, module_area: entry.f2, generated_by: entry.f3, status: entry.f4, file_url: entry.f5 };
          if (editId) await supabaseDb.from('reports').update(repData).eq('id', editId);
          else await supabaseDb.from('reports').insert([repData]);
        } catch(e) { console.error(e); }
      } else if (currentGenericModule === 'Academic_TeacherProfiles' && supabaseDb) {
        try {
          let tpData = { teacher_name: entry.f1, teacher_role: entry.f2, teacher_email: entry.f3, teacher_phone: entry.f4, teacher_description: entry.f5, teacher_image_url: entry.f6, is_active: (entry.f7 === 'Active') };
          if (editId) await supabaseDb.from('teacher_profiles').update(tpData).eq('id', editId);
          else await supabaseDb.from('teacher_profiles').insert([tpData]);
        } catch(e) { console.error(e); }
      }

      // Also save to localStorage`;

content = content.replace(`      } else if (currentGenericModule === 'Academic_Report' && supabaseDb) {
        try {
          let repData = { report_title: entry.f1, module_area: entry.f2, generated_by: entry.f3, status: entry.f4, file_url: entry.f5 };
          if (editId) await supabaseDb.from('reports').update(repData).eq('id', editId);
          else await supabaseDb.from('reports').insert([repData]);
        } catch(e) { console.error(e); }
      }

      // Also save to localStorage`, submitInjection);


fs.writeFileSync(file, content);
console.log("Teacher profiles integration added successfully.");
